StudentPeriodScreen
Gabuardi/career-plan pull request #15
Opened 2021-12-05 00:23 UTC by Ozamoram429-bit

2021-12-05 03:49 UTC, Gabuardi commented on CareerPlan/CareerPlan.csproj
> +  </ItemGroup>
This was added manually or auto-generated?

2021-12-05 04:22 UTC, Ozamoram429-bit commented on CareerPlan/CareerPlan.csproj
> +  </ItemGroup>
Auto-generated!

2021-12-05 17:25 UTC, Gabuardi requested changes

2021-12-05 17:25 UTC, Gabuardi commented on CareerPlan/CareerPlan.csproj
> +  </ItemGroup>
I think we can remove it, we don't need it

2021-12-05 17:25 UTC, Gabuardi commented on CareerPlan/Views/StudentPeriod.xaml
> +            </Frame>
We don't need this, just add the `Title` atribute to the `ContentPage` 

```xaml
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="CareerPlan.Views.StudentPeriodPage"
             Title="Añadir Periodo Estudiantil">
```

2021-12-06 01:01 UTC, Gabuardi approved these changes

2021-12-07 02:22 UTC, merged